# Generated by Django 6.0.6 on 2026-06-07 21:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('mise', models.PositiveIntegerField()),
                ('nb_collectes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Cloture')], default='EN_COURS', max_length=30)),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cycle',
                'verbose_name_plural': 'cycles',
                'ordering': ['-date_ouverture', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mise__gt', 0)), name='cycle_mise_gt_0'), models.CheckConstraint(condition=models.Q(('nb_collectes__gte', 0), ('nb_collectes__lte', 31)), name='cycle_nb_collectes_between_0_31')],
            },
        ),
    ]
