# Generated by Django 6.0.6 on 2026-06-07 21:46

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agent_adresse_agent_created_by_agent_deleted_at_and_more'),
        ('clients', '0001_initial'),
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nb_mises', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('montant', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='agents.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='cycles.cycle')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'depot',
                'verbose_name_plural': 'depots',
                'ordering': ['-date_depot', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('montant', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_retrait', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits', to='agents.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'retrait',
                'verbose_name_plural': 'retraits',
                'ordering': ['-date_retrait', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('MISE', 'Mise'), ('RETENUE', 'Retenue'), ('COM_AGENT', 'Commission agent'), ('COM_INSTITUTION', 'Commission institution'), ('CREDIT_CLIENT', 'Credit client'), ('RETRAIT', 'Retrait')], max_length=50)),
                ('sens', models.CharField(choices=[('ENTREE', 'Entree'), ('SORTIE', 'Sortie'), ('INFO', 'Information')], max_length=20)),
                ('montant', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('reference_operation', models.CharField(blank=True, max_length=100)),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='agents.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='cycles.cycle')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement',
                'verbose_name_plural': 'mouvements',
                'ordering': ['-date_mouvement', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('client__isnull', True), ('cycle__isnull', True), ('agent__isnull', True), _negated=True), name='mouvement_has_at_least_one_relation')],
            },
        ),
        migrations.CreateModel(
            name='Retenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('montant', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('commission_agent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_institution', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_retenue', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenues', to='agents.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenues', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retenue', to='cycles.cycle')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'retenue',
                'verbose_name_plural': 'retenues',
                'ordering': ['-date_retenue', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gte', django.db.models.expressions.CombinedExpression(models.F('commission_agent'), '+', models.F('commission_institution')))), name='retenue_commissions_not_exceed_montant')],
            },
        ),
    ]
